CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Events" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Title" character varying(200) NOT NULL,
    "Description" character varying(1000) NOT NULL,
    "Date" timestamp with time zone NOT NULL,
    "UserId" text,
    CONSTRAINT "PK_Events" PRIMARY KEY ("Id")
);

CREATE INDEX "IX_Events_Date" ON "Events" ("Date");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20241216171054_InitialCreate', '8.0.11');

COMMIT;

START TRANSACTION;

ALTER TABLE "Events" ALTER COLUMN "Description" DROP NOT NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20241217200059_eventNullable', '8.0.11');

COMMIT;

