CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Calendars" (
    "Id" uuid NOT NULL,
    "Name" character varying(100) NOT NULL,
    "ShareableLink" character varying(100) NOT NULL,
    "IsDefault" boolean NOT NULL,
    "CountryCode" character varying(2) NOT NULL,
    "IsDefaultCountryCalendar" boolean NOT NULL,
    "IsUserCreated" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" bigint NOT NULL,
    "ModifiedAt" timestamp with time zone,
    "ModifiedBy" bigint,
    CONSTRAINT "PK_Calendars" PRIMARY KEY ("Id")
);

CREATE TABLE "Countries" (
    "Id" uuid NOT NULL,
    "CountryCode" text NOT NULL,
    "CountryName" text NOT NULL,
    "IsActive" boolean NOT NULL,
    "Description" text,
    "DisplayOrder" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" bigint NOT NULL,
    "ModifiedAt" timestamp with time zone,
    "ModifiedBy" bigint,
    CONSTRAINT "PK_Countries" PRIMARY KEY ("Id")
);

CREATE TABLE "EventTypes" (
    "Id" uuid NOT NULL,
    "Name" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" bigint NOT NULL,
    "ModifiedAt" timestamp with time zone,
    "ModifiedBy" bigint,
    CONSTRAINT "PK_EventTypes" PRIMARY KEY ("Id")
);

CREATE TABLE "Holidays" (
    "Id" uuid NOT NULL,
    "Name" text NOT NULL,
    "Date" timestamp with time zone NOT NULL,
    "IsFixedHoliday" boolean NOT NULL,
    "IsWeekendAdjustable" boolean NOT NULL,
    "Description" text,
    "IsDefault" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" bigint NOT NULL,
    "ModifiedAt" timestamp with time zone,
    "ModifiedBy" bigint,
    CONSTRAINT "PK_Holidays" PRIMARY KEY ("Id")
);

CREATE TABLE "Roles" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text,
    CONSTRAINT "PK_Roles" PRIMARY KEY ("Id")
);

CREATE TABLE "Users" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "CreatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" bigint NOT NULL,
    "ModifiedAt" timestamp with time zone,
    "ModifiedBy" bigint,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

CREATE TABLE "CalendarShares" (
    "Id" uuid NOT NULL,
    "CalendarId" uuid NOT NULL,
    "ShareableLink" text NOT NULL,
    "ExpiryDate" timestamp with time zone NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" bigint NOT NULL,
    "ModifiedAt" timestamp with time zone,
    "ModifiedBy" bigint,
    CONSTRAINT "PK_CalendarShares" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_CalendarShares_Calendars_CalendarId" FOREIGN KEY ("CalendarId") REFERENCES "Calendars" ("Id") ON DELETE CASCADE
);

CREATE TABLE "ExportLogs" (
    "Id" uuid NOT NULL,
    "CalendarId" uuid NOT NULL,
    "ExportType" text NOT NULL,
    "ExportDate" timestamp with time zone NOT NULL,
    "ExportedBy" text NOT NULL,
    "ExportFormat" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" bigint NOT NULL,
    "ModifiedAt" timestamp with time zone,
    "ModifiedBy" bigint,
    CONSTRAINT "PK_ExportLogs" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ExportLogs_Calendars_CalendarId" FOREIGN KEY ("CalendarId") REFERENCES "Calendars" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Events" (
    "Id" uuid NOT NULL,
    "Name" character varying(200) NOT NULL,
    "Description" character varying(500) NOT NULL,
    "StartDate" timestamp with time zone NOT NULL,
    "EndDate" timestamp with time zone NOT NULL,
    "CalendarId" uuid NOT NULL,
    "EventTypeId" uuid NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" bigint NOT NULL,
    "ModifiedAt" timestamp with time zone,
    "ModifiedBy" bigint,
    CONSTRAINT "PK_Events" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Events_Calendars_CalendarId" FOREIGN KEY ("CalendarId") REFERENCES "Calendars" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Events_EventTypes_EventTypeId" FOREIGN KEY ("EventTypeId") REFERENCES "EventTypes" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "CalendarHolidays" (
    "Id" uuid NOT NULL,
    "CalendarId" uuid NOT NULL,
    "HolidayId" uuid NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" bigint NOT NULL,
    "ModifiedAt" timestamp with time zone,
    "ModifiedBy" bigint,
    CONSTRAINT "PK_CalendarHolidays" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_CalendarHolidays_Calendars_CalendarId" FOREIGN KEY ("CalendarId") REFERENCES "Calendars" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_CalendarHolidays_Holidays_HolidayId" FOREIGN KEY ("HolidayId") REFERENCES "Holidays" ("Id") ON DELETE CASCADE
);

CREATE TABLE "RoleClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" bigint NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_RoleClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_RoleClaims_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Roles" ("Id") ON DELETE CASCADE
);

CREATE TABLE "UserCalendars" (
    "Id" uuid NOT NULL,
    "UserId" bigint NOT NULL,
    "CalendarId" uuid NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" bigint NOT NULL,
    "ModifiedAt" timestamp with time zone,
    "ModifiedBy" bigint,
    CONSTRAINT "PK_UserCalendars" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_UserCalendars_Calendars_CalendarId" FOREIGN KEY ("CalendarId") REFERENCES "Calendars" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_UserCalendars_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "UserClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" bigint NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_UserClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_UserClaims_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "UserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" bigint NOT NULL,
    CONSTRAINT "PK_UserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_UserLogins_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "UserRoles" (
    "UserId" bigint NOT NULL,
    "RoleId" bigint NOT NULL,
    CONSTRAINT "PK_UserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_UserRoles_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Roles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_UserRoles_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "UserTokens" (
    "UserId" bigint NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text,
    CONSTRAINT "PK_UserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_UserTokens_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_CalendarHolidays_CalendarId" ON "CalendarHolidays" ("CalendarId");

CREATE INDEX "IX_CalendarHolidays_HolidayId" ON "CalendarHolidays" ("HolidayId");

CREATE UNIQUE INDEX "IX_Calendars_Name_CountryCode" ON "Calendars" ("Name", "CountryCode") WHERE "IsDefault" = true;

CREATE INDEX "IX_CalendarShares_CalendarId" ON "CalendarShares" ("CalendarId");

CREATE UNIQUE INDEX "IX_CalendarShares_ShareableLink" ON "CalendarShares" ("ShareableLink");

CREATE INDEX "IX_Events_CalendarId_StartDate_EndDate" ON "Events" ("CalendarId", "StartDate", "EndDate");

CREATE INDEX "IX_Events_EventTypeId" ON "Events" ("EventTypeId");

CREATE INDEX "IX_ExportLogs_CalendarId" ON "ExportLogs" ("CalendarId");

CREATE INDEX "IX_RoleClaims_RoleId" ON "RoleClaims" ("RoleId");

CREATE UNIQUE INDEX "RoleNameIndex" ON "Roles" ("NormalizedName");

CREATE INDEX "IX_UserCalendars_CalendarId" ON "UserCalendars" ("CalendarId");

CREATE UNIQUE INDEX "IX_UserCalendars_UserId_CalendarId" ON "UserCalendars" ("UserId", "CalendarId");

CREATE INDEX "IX_UserClaims_UserId" ON "UserClaims" ("UserId");

CREATE INDEX "IX_UserLogins_UserId" ON "UserLogins" ("UserId");

CREATE INDEX "IX_UserRoles_RoleId" ON "UserRoles" ("RoleId");

CREATE INDEX "EmailIndex" ON "Users" ("NormalizedEmail");

CREATE UNIQUE INDEX "UserNameIndex" ON "Users" ("NormalizedUserName");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250109181752_InitialCreate', '8.0.11');

COMMIT;

START TRANSACTION;

ALTER TABLE "UserCalendars" ADD "CountryCode" text NOT NULL DEFAULT '';

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250110171510_UpdatedUserCalendar', '8.0.11');

COMMIT;

